algo = input('Digite algo: ')
print('Se condição for VERDADEIRA irá aparecer True, se for FALSO irá aparecer False')
print('O que você digitou é numero? {}'.format(algo.isnumeric()))
print('O que você digitou é um numero racional? {}'.format(algo.isdecimal()))
print('O que você digitou é alfabetico? {}'.format(algo.isalpha()))
print('O que você digitou é alfanumerico? {}'.format(algo.isalnum()))
print('O que você digitou está em caixa alta? {}'.format(algo.isupper()))
print('O que você digitou está em letra minuscula? {}'.format(algo.islower()))
print('O que você digitou é um espaço? {}'.format(algo.isspace()))
