print('------ DESAFIO 02 ------')
dia = input('Qual o dia do seu aniversário? ')
mes = input('Qual o mês do seu aniversário? ')
ano = input('Qual o nasc do seu aniversário? ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto?')
